name: "Deploy NextJS VPS Hostinger"
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executar git pull no servidor
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /projects
            echo "PWD inicial:"
            pwd
            echo "Conteúdo de /projects:"
            ls -la /root/projects

            if [ ! -d "/root/projects/portfolio-jandernery/.git" ]; then
                echo "Clonando repositório..."
                git clone https://github.com/jnerydesigner/portfolio-jandernery /root/projects/portfolio-jandernery
            else
                echo "Repositório já clonado"
            fi

            echo "Entrando na pasta do projeto"
            cd /root/projects/portfolio-jandernery
            echo "PWD após cd:"
            pwd
            echo "Conteúdo da pasta do projeto:"
            ls -la

            echo "Executando git pull"
            git pull origin main

      - name: Instalar as dependencias
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/projects/portfolio-jandernery
            yarn install

      - name: Executar o Build No Servidor
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/projects/portfolio-jandernery
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
            yarn build

      - name: Executar o PM2 e Start No Servidor
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/projects/portfolio-jandernery
            pm2 update portfolio-jandernery || true
            pm2 start my-pm2-start.json --update-env || pm2 restart my-pm2-start.json
